image: hseeberger/scala-sbt:8u265_1.4.5_2.13.4

cache:
  paths:
    - .ivy2/cache
    - .sbt/boot/
  key: ${CI_PROJECT_NAME}

before_script:
  - apt-get install -y ca-certificates wget
  - export GPG_TTY=$(tty) # https://stackoverflow.com/a/55032706
  - export GNUPGHOME=`pwd`/.gnupg # https://serverfault.com/a/528355
  - gpg --version
  - ps aux | grep gpg
  
  - export GPG_PATH=`pwd`/.gpg
  - mkdir $GPG_PATH
  - echo ${PGP_PUBRING} > $GPG_PATH/pubring.asc
  - echo ${PGP_SECRING} > $GPG_PATH/secring.asc
  - gpg --import <(echo "$PGP_SECRING") # https://stackoverflow.com/a/43732926
  - gpg --list-key

after_script:
  # Tricks to avoid unnecessary cache updates
  - find `pwd`/.ivy2 -name "ivydata-*.properties" -delete
  - find `pwd`/.sbt -name "*.lock" -delete

stages:
# - test
  - publish

#test:
#  stage: test
#  script:
#    - sbt -Dsbt.ivy.home=`pwd`/.ivy2 -Dsbt.boot.directory=`pwd`/.sbt/boot ";clean;test"

publish:
  stage: publish
  #only:
  #  - snapshot
  script:
    - sbt -Dsbt.ivy.home=`pwd`/.ivy2 -Dsbt.boot.directory=`pwd`/.sbt/boot ";update;+publishSigned"
