image: hseeberger/scala-sbt

cache:
  paths:
    - .ivy2/cache
    - .sbt/boot/
  key: ${CI_PROJECT_NAME}

before_script:
  - export PGP_PATH=`pwd`/.pgp
  - mkdir $PGP_PATH
  - echo ${PGP_PUBRING} > $PGP_PATH/pubring.asc
  - echo ${PGP_SECRING} > $PGP_PATH/secring.asc

after_script:
  # Tricks to avoid unnecessary cache updates
  - find `pwd`/.ivy2 -name "ivydata-*.properties" -delete
  - find `pwd`/.sbt -name "*.lock" -delete

stages:
  - test
  - publish

test:
  stage: test
  script:
    - sbt -Dsbt.ivy.home=`pwd`/.ivy2 -Dsbt.boot.directory=`pwd`/.sbt/boot ";clean;coverage;test;coverageReport"
    - mkdir scoverage-report
    - cp -R target/scala-2.12/scoverage-report/* scoverage-report/
  artifacts:
    name: scoverage-report
    paths:
      - scoverage-report/*

publish:
  stage: publish
  only:
    - snapshot
  script:
    - sbt -Dsbt.ivy.home=`pwd`/.ivy2 -Dsbt.boot.directory=`pwd`/.sbt/boot ";update;+publishSigned"
