image: registry.gitlab.com/developtheweb/sbt-scala-ci-image:java17-latest

cache:
  paths:
    - .ivy2/cache
    - .sbt/boot/
  key: ${CI_PROJECT_NAME}

after_script:
  # Tricks to avoid unnecessary cache updates
  - find `pwd`/.ivy2 -name "ivydata-*.properties" -delete
  - find `pwd`/.sbt -name "*.lock" -delete

stages:
  - test
  - publish

test:
  stage: test
  script:
    - sbt -Dsbt.ivy.home=`pwd`/.ivy2 -Dsbt.boot.directory=`pwd`/.sbt/boot ";clean;test"

publish:
  stage: publish
  only:
    - snapshot
  before_script:
    - gpg --batch --import <(echo "$PGP_SECRING")
  script:
    - sbt -Dsbt.ivy.home=`pwd`/.ivy2 -Dsbt.boot.directory=`pwd`/.sbt/boot ";update;+publishSigned"
